# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardVisionSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_numer', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('scene', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('img_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InfraredSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_number', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('sensor_a', models.IntegerField()),
                ('sensor_b', models.IntegerField()),
                ('sensor_c', models.IntegerField()),
                ('sensor_d', models.IntegerField()),
                ('sensor_e', models.IntegerField()),
                ('sensor_f', models.IntegerField()),
                ('sensor_g', models.IntegerField()),
                ('sensor_h', models.IntegerField()),
                ('sensor_i', models.IntegerField()),
                ('sensor_j', models.IntegerField()),
                ('sensor_k', models.IntegerField()),
                ('sensor_l', models.IntegerField()),
                ('sensor_m', models.IntegerField()),
                ('sensor_n', models.IntegerField()),
                ('sensor_o', models.IntegerField()),
                ('sensor_p', models.IntegerField()),
                ('sensor_q', models.IntegerField()),
                ('sensor_r', models.IntegerField()),
                ('sensor_s', models.IntegerField()),
                ('sensor_t', models.IntegerField()),
                ('sensor_u', models.IntegerField()),
                ('sensor_v', models.IntegerField()),
                ('sensor_w', models.IntegerField()),
                ('sensor_x', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KinectDeepSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_numer', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('scene', models.CharField(max_length=64)),
                ('deep_filename', models.CharField(max_length=64)),
                ('deep_path', models.CharField(max_length=256)),
                ('mapped_img_filename', models.CharField(max_length=64)),
                ('mapped_img_path', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='KinectVideoSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_numer', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('scene', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('img_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaserSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_numer', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('scene', models.CharField(max_length=64)),
                ('data_filename', models.CharField(max_length=64)),
                ('file_path', models.CharField(max_length=256)),
                ('area_a', models.CharField(max_length=64)),
                ('area_b', models.CharField(max_length=64)),
                ('area_c', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='OverallViewSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_numer', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('scene', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=64)),
                ('img_path', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UltrasonicSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField()),
                ('robot_number', models.CharField(max_length=256)),
                ('robot_posture', models.CharField(max_length=64)),
                ('sensor_a', models.IntegerField()),
                ('sensor_b', models.IntegerField()),
                ('sensor_c', models.IntegerField()),
                ('sensor_d', models.IntegerField()),
                ('sensor_e', models.IntegerField()),
                ('sensor_f', models.IntegerField()),
                ('sensor_g', models.IntegerField()),
                ('sensor_h', models.IntegerField()),
                ('sensor_i', models.IntegerField()),
                ('sensor_j', models.IntegerField()),
                ('sensor_k', models.IntegerField()),
                ('sensor_l', models.IntegerField()),
                ('sensor_m', models.IntegerField()),
                ('sensor_n', models.IntegerField()),
                ('sensor_o', models.IntegerField()),
                ('sensor_p', models.IntegerField()),
                ('sensor_q', models.IntegerField()),
                ('sensor_r', models.IntegerField()),
                ('sensor_s', models.IntegerField()),
                ('sensor_t', models.IntegerField()),
                ('sensor_u', models.IntegerField()),
                ('sensor_v', models.IntegerField()),
                ('sensor_w', models.IntegerField()),
                ('sensor_x', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
